import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { API_BASE } from '../../config';

export default function CategoryForm({ category, onClose, onSaved }) {
  const isEdit = !!category;
  const { token } = useAuth();
  const [title, setTitle] = useState(category?.title || '');
  const [description, setDescription] = useState(category?.description || '');
  const [submitting, setSubmitting] = useState(false);
  const [status, setStatus] = useState({ kind: null, text: '' });

  async function handleSubmit(e) {
    e.preventDefault();
    setSubmitting(true);
    try {
      const payload = {
        title: title.trim(),
        description: description || null,
        // slug will be auto-generated by backend; schema defaults are also applied
      };
      const url = isEdit ? `${API_BASE}/tourism/categories/${category.id}` : `${API_BASE}/tourism/categories`;
      const method = isEdit ? 'PUT' : 'POST';
      const r = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      if (!r.ok) {
        const e = await r.json().catch(()=>({}));
        throw new Error(e.error || 'Failed to save category');
      }
      setStatus({ kind: 'success', text: 'Saved successfully.' });
      setTimeout(() => { setStatus({ kind: null, text: '' }); onSaved?.(); onClose?.(); }, 2000);
    } catch (err) {
      setStatus({ kind: 'error', text: err.message || 'An error occurred.' });
      setTimeout(() => setStatus({ kind: null, text: '' }), 2000);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4 p-1 sm:p-2">
      <div>
        <label className="block text-sm text-gray-700">Title</label>
        <input value={title} onChange={(e)=>setTitle(e.target.value)} className="w-full border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" required />
      </div>
      <div>
        <label className="block text-sm text-gray-700">Description</label>
        <textarea value={description} onChange={(e)=>setDescription(e.target.value)} rows={2} className="w-full border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
      </div>
      {status.kind ? (
        <div className={`px-4 py-2 rounded-md text-sm ${status.kind==='success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>{status.text}</div>
      ) : (
        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} className="px-4 py-2 rounded-md border">Cancel</button>
          <button disabled={submitting} className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">{submitting ? 'Saving...' : (isEdit ? 'Save' : 'Create')}</button>
        </div>
      )}
    </form>
  );
}
